### ISSUE TITLE
Appimage get crash with Hollow Knight (367520) , Grotto (1538850)

### ISSUE THREAD

**Issue by bg2908** [jsnli/Samira#3]
App crashed after choose game from database list. 

> [S_API] SteamAPI_Init(): Loaded '/home/sheercold/.local/share/Steam/linux64/steamclient.so' OK.
> Setting breakpad minidump AppID = 1764390
> SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198077521746 [API loaded no]
> User Stats Received.
> [S_API] SteamAPI_Init(): Loaded '/home/sheercold/.local/share/Steam/linux64/steamclient.so' OK.
> Setting breakpad minidump AppID = 1538850
> SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198077521746 [API loaded no]
> User Stats Received.
> thread 'main' panicked at src/steam.rs:177:58:
> Not a valid minimum number: ParseIntError { kind: InvalidDigit }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at library/core/src/panicking.rs:221:5:
> panic in a function that cannot unwind
> stack backtrace:
>    0:     0x61d21e47ef65 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h1b9dad2a88e955ff
>    1:     0x61d21e4a828b - core::fmt::write::h4b5a1270214bc4a7
>    2:     0x61d21e47beef - std::io::Write::write_fmt::hd04af345a50c312d
>    3:     0x61d21e480261 - std::panicking::default_hook::{{closure}}::h96ab15e9936be7ed
>    4:     0x61d21e47ff3c - std::panicking::default_hook::h3cacb9c27561ad33
>    5:     0x61d21e4808c1 - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
>    6:     0x61d21e4806f3 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
>    7:     0x61d21e47f429 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
>    8:     0x61d21e4803b4 - rust_begin_unwind
>    9:     0x61d21deb4cf5 - core::panicking::panic_nounwind_fmt::h4c4dc67d0bbc166c
>   10:     0x61d21deb4d82 - core::panicking::panic_nounwind::hb98133c151c787e4
>   11:     0x61d21deb4ec6 - core::panicking::panic_cannot_unwind::he9511e6e72319a3e
>   12:     0x61d21e13dff6 - <O as webkit2gtk::auto::user_content_manager::UserContentManagerExt>::connect_script_message_received::script_message_received_trampoline::h9624021b55850f30
>   13:     0x7f7f5b3ae2fa - g_closure_invoke
>   14:     0x7f7f5b3dd90c - <unknown>
>   15:     0x7f7f5b3ce591 - <unknown>
>   16:     0x7f7f5b3ce7c1 - g_signal_emit_valist
>   17:     0x7f7f5b3ce883 - g_signal_emit
>   18:     0x7f7f5e39571f - <unknown>
>   19:     0x7f7f5e422aaa - <unknown>
>   20:     0x7f7f5dfdab36 - <unknown>
>   21:     0x7f7f5dfd9ad0 - <unknown>
>   22:     0x7f7f5e1f0a3b - <unknown>
>   23:     0x7f7f5e2a54e7 - <unknown>
>   24:     0x7f7f5e1e95e5 - <unknown>
>   25:     0x7f7f5e1eb681 - <unknown>
>   26:     0x7f7f5c700aed - <unknown>
>   27:     0x7f7f5c75d27d - <unknown>
>   28:     0x7f7f5c75db93 - <unknown>
>   29:     0x7f7f5b2a248e - <unknown>
>   30:     0x7f7f5b301717 - <unknown>
>   31:     0x7f7f5b2a1a53 - g_main_context_iteration
>   32:     0x7f7f5d1fec6d - gtk_main_iteration_do
>   33:     0x61d21e1a3e4b - gtk::auto::functions::main_iteration_do::h0e241e44aa359c64
>   34:     0x61d21df8e783 - glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default::hf827d20d5af7e29e
>   35:     0x61d21df18047 - tao::platform_impl::platform::event_loop::EventLoop<T>::run::ha138d0d2c03df20d
>   36:     0x61d21df24656 - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::he48b497b78c25540
>   37:     0x61d21df5fb92 - tauri::app::Builder<R>::run::hb4bc1d5aa8288aba
>   38:     0x61d21deee193 - tokio::runtime::context::runtime::enter_runtime::h89c054ac36c8f20f
>   39:     0x61d21dfda441 - samira::main::h9d476a1037237125
>   40:     0x61d21dfa9a63 - std::sys::backtrace::__rust_begin_short_backtrace::h3825abe1dee5ecbc
>   41:     0x61d21df98359 - std::rt::lang_start::{{closure}}::h94db031b6411f46f
>   42:     0x61d21e474b60 - std::rt::lang_start_internal::h5e7c81cecd7f0954
>   43:     0x61d21dfdb865 - main
>   44:     0x7f7f5af751ce - <unknown>
>   45:     0x7f7f5af7528a - __libc_start_main
>   46:     0x61d21deb5645 - _start
>   47:                0x0 - <unknown>
> thread caused non-unwinding panic. aborting.
> [1]    27772 IOT instruction (core dumped)  ./samira_0.1.0_amd64.AppImage

**Comment by jsnli** [comment]
A fix is available in the newest release [v0.3.0](https://github.com/jsnli/Samira/releases/tag/v0.3.0).

I was able to reproduce and confirm the fix for Hollow Knight. I don't own Grotto, please let me know if there are any issues with this game. Thanks for reporting this issue.

**Comment by bg2908** [comment]
Thanks. Confirm that both Grotto an Hollow Knight not crashed anymore.
