### ISSUE TITLE
Lock Achievements 

### ISSUE THREAD

**Issue by JokerGermany** [jsnli/Samira#8]
It looks like you only can unlock Achievements.
I would like to be able to lock (all unlocked) Achievements (of an account)

**Comment by jsnli** [comment]
I'm currently away for the holidays until December. For now, can you list your distro, version number and brief steps to reproduce?  Happy to take a look when I'm back. Thanks.

**Comment by jsnli** [comment]
Lock functionality is working. If you are having issues, it's most likely related to games like Rocket League that have been delisted which means I don't have the ability to reproduce this error.
